name: Build Pacman package

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-linux:
    name: Build Pacman packages (Linux)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64, aarch64]
    steps:
      # + avoid recursive clone, as submodules are cloned again by makepkg
      - name: Clone project
        uses: actions/checkout@v4

      - name: Setup Alpine Linux
        uses: jirutka/setup-alpine@v1
        with:
          branch: v3.20
          arch: ${{ matrix.arch }}
          packages: >
            build-base
            fakeroot
            git
            curl
            bash
            libarchive-tools
            xz
            zstd
            sudo
            coreutils
            sed
            patchelf

      - name: Install Wonderful
        run: |
          sudo sh -c "mkdir /opt/wonderful && cd /opt/wonderful && curl https://wonderful.asie.pl/bootstrap/wf-bootstrap-${{ matrix.arch }}.tar.gz | tar xzvf -"
        shell: alpine.sh --root {0}

      - name: Install prerequisites (Wonderful)
        run: |
          /opt/wonderful/bin/wf-pacman -Syu --noconfirm wonderful-base
        shell: alpine.sh --root {0}

      # FIXME: The first launch of fakeroot via wf-makepkg seems to emit a SIGUSR1 in this environment.
      # Thankfully, executing it again picks up right where it left off.
      - name: Build package
        run: |
           cd ${{ github.workspace }}/pacman && export PATH=/opt/wonderful/bin:$PATH && ( wf-makepkg -s --noconfirm || true ) && wf-makepkg -s --noconfirm
        shell: alpine.sh {0}

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Pacman packages (Linux, ${{ matrix.arch }})
          path: ${{ github.workspace }}/pacman/*.pkg.tar.xz

